spring:
    profiles:
        active:
        - dev
        
---
spring:
    profiles: dev
    application:
        name: microconfig-test-dec
        
---
spring:
    profiles: default
    application:
        name: microconfig-test-default
