spring:
    profiles:
        active:
        - dev
---
server:
    port: 8064
mybatis:
  mapper-locations:
  - classpath*:cn.enjoy.mapping/*.xml
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.61.21.185:15018/ccrs?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ph123456
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
  application:
    name: springCloud-provider-shop #eureka前面的名字
  profiles: dev
  
logging:
  config: classpath:logback-spring-dev.xml
  level: 
    cn.enjoy.mapper: debug
    org.springframework.boot: ERROR  #关闭spring启动时无用日志
    
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
  instance:
    instance-id: springCloud-provider-shop #eureka后面的名字
    prefer-ip-address: true #鼠标放到eureka后面的名字左下角显示ip
    lease-renewal-interval-in-seconds: 30 #设置心跳的时间，默认是30秒
    lease-expiration-duration-in-seconds: 90 #如果现在超过了5秒的间隔就表示注册中心挂了（默认是90秒）
    status-page-url: http://localhost:${server.port}/swagger-ui.html

feign: 
  hystrix: 
    enabled: true
  compression: 
    request: 
      enabled: true 
      mime-types: #可以被压缩的类型 
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 #超过2048字节压缩
ribbon:
  eager-load:
    enabled: true #解决第一次加载没有服务的问题
    clients:
    - SPRINGCLOUD-ZUUL-GATEWAY,SPRINGCLOUD-PROVIDER_USER,SPRINGCLOUD-REDIS,SPRINGCLOUD-CONSUMER-RABBITMQ,SPRINGCLOUD-PROVIDER-ORDER

    
info:
  app.name: springcloud-provider-shop
  company.name: enjoy11
  app.imgLocation: /usr/rs/Img/
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
management:
    endpoints:
        web:
            exposure: 
                include: '*'
                
---
