spring:
    profiles:
        active:
        - dev
---
server:
    port: 8062
mybatis:
  mapper-locations:
  - classpath*:cn.enjoy.mapping/*.xml
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.61.21.185:15018/ccrs?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ph123456
  application:
    name: springCloud-provider-project #eureka前面的名字
  profiles: dev
  
logging:
  config: classpath:logback-spring.xml
  level: 
    cn.enjoy.mapper: debug
    org.springframework.boot: ERROR  #关闭spring启动时无用日志
    
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
  instance:
    instance-id: springCloud-provider-project #eureka后面的名字
    prefer-ip-address: true #鼠标放到eureka后面的名字左下角显示ip
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间，默认是30秒
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔就表示注册中心挂了（默认是90秒）
    status-page-url: http://localhost:${server.port}/swagger-ui.html
    
info:
  app.name: springcloud-provider-project
  company.name: enjoy11
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
management:
    endpoints:
        web:
            exposure: 
                include: '*'
                
---
