spring:
    profiles:
        active:
        - dev
---
server:
    port: 7001
eureka:
    service:
        eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认60秒）
        enable-self-preservation: false #设置为false表示关闭保护模式
    client: 
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://admin:enjoy@localhost:7001/eureka
    instance:
        hostname: localhost #定义eureka实例所在主机

spring:
    profiles: bate
    security: 
        user:
            name: admin
            password: enjoy
    application: 
        name: springCloud-config-eureka-client
        
---
server:
    port: 7002
eureka:
    service:
        eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认60秒）
        enable-self-preservation: false #设置为false表示关闭保护模式
    client: 
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://admin:enjoy@localhost:7002/eureka
    instance:
        hostname: localhost #定义eureka实例所在主机

spring:
    profiles: dev
    security: 
        user:
            name: admin
            password: enjoy
    application: 
        name: springCloud-config-eureka-client
