spring:
    profiles:
        active:
        - dev
---
server:
    port: 7972

spring:
  application:
    name: springCloud-batch #eureka前面的名字
  profiles: dev
  
feign: 
  hystrix: 
    enabled: true
  compression: 
    request: 
      enabled: true 
      mime-types: #可以被压缩的类型 
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 #超过2048字节压缩
      
ribbon:
  eager-load:
    enabled: true #解决第一次加载没有服务的问题
    clients:
    - SPRINGCLOUD-ZUUL-GATEWAY,SPRINGCLOUD-PROVIDER_USER,SPRINGCLOUD-REDIS,SPRINGCLOUD-PROVIDER_SHOP,SPRINGCLOUD-PROVIDER-ORDER,SPRINGCLOUD-CONSUMER_RABBITMQ

    
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
    register-with-eureka: false
  instance:
    instance-id: springCloud-batch #eureka后面的名字
    prefer-ip-address: true #鼠标放到eureka后面的名字左下角显示ip
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间，默认是30秒
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔就表示注册中心挂了（默认是90秒）
    
info:
  app.name: springCloud-batch
  company.name: enjoy11
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
logging:
  config: classpath:logback-spring-dev.xml
  level: 
    org.springframework.boot: ERROR  #关闭spring启动时无用日志

  
management:
    endpoints:
        web:
            exposure: 
                include: '*'
                
---
