spring:
    profiles:
        active:
        - dev
---
server:
    port: 8061
mybatis:
  mapper-locations:
  - classpath*:cn.enjoy.mapping/*.xml
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.61.21.185:15018/ccrs?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ph123456
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
  application:
    name: springCloud-provider-order #eureka前面的名字
  profiles: dev
  
logging:
  config: classpath:logback-spring-dev.xml
  level: 
    cn.enjoy.mapper: debug
    org.springframework.boot: ERROR  #关闭spring启动时无用日志

feign: 
  hystrix: 
    enabled: true
  compression: 
    request: 
      enabled: true 
      mime-types: #可以被压缩的类型 
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 #超过2048字节压缩
      
ribbon:
  eager-load:
    enabled: true #解决第一次加载没有服务的问题
    clients:
    - SPRINGCLOUD-ZUUL-GATEWAY,SPRINGCLOUD-PROVIDER_USER,SPRINGCLOUD-REDIS,SPRINGCLOUD-PROVIDER_SHOP,SPRINGCLOUD-CONSUMER_RABBITMQ

# 是否启动LCN负载均衡策略(优化选项，开启与否，功能不受影响)
tx-lcn:
  ribbon:                #微服务集群且用到 LCN事务模式时，为保证性能请开启TX-LCN重写的负载策略
    loadbalancer:
      dtx:
        enabled: true
  client:                # tx-manager 的配置地址，可以指定TM集群中的任何一个或多个地址
    manager-address:
    - 127.0.0.1:8070
    chain-level: 3       # 调用链长度等级，默认值为3（优化选项。系统中每个请求大致调用链平均长度，估算值。）
    
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
  instance:
    instance-id: springCloud-provider-order #eureka后面的名字
    prefer-ip-address: true #鼠标放到eureka后面的名字左下角显示ip
    lease-renewal-interval-in-seconds: 30 #设置心跳的时间，默认是30秒
    lease-expiration-duration-in-seconds: 90 #如果现在超过了5秒的间隔就表示注册中心挂了（默认是90秒）
    status-page-url: http://localhost:${server.port}/swagger-ui.html
    
info:
  app.name: springcloud-provider-order
  company.name: enjoy11
  weChat.appId: wx5963cfc0f6ecd620
  weChat.mchId: 1514514091
  weChat.appKey: 0494d9a8fb9da2f80ae95dbb6ff95c63
  weChat.appSecret: 1d899a166f4831deef02d5ee79a95231
  weChat.payUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  weChat.notifyUrl: https://119.61.21.185:15011/weChat/payCallBack 
  build.arti.factId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
management:
    endpoints:
        web:
            exposure: 
                include: '*'
                
---

server:
    port: 8091
mybatis:
  mapper-locations:
  - classpath*:cn.enjoy.mapping/*.xml
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.61.21.185:15018/springcloud?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ph123456
  application:
    name: springCloud-provider-order #eureka前面的名字
  profiles: pro
  
logging:
  config: classpath:logback-spring.xm
  level: 
    cn.enjoy.mapper: debug
    org.springframework.boot: ERROR  #关闭spring启动时无用日志
    
#对整个接口的熔断处理方案
feign: 
  hystrix: 
    enabled: true 
    
# 是否启动LCN负载均衡策略(优化选项，开启与否，功能不受影响)
tx-lcn:
  ribbon:                #微服务集群且用到 LCN事务模式时，为保证性能请开启TX-LCN重写的负载策略
    loadbalancer:
      dtx:
        enabled: true
  client:                # tx-manager 的配置地址，可以指定TM集群中的任何一个或多个地址
    manager-address:
    - 127.0.0.1:8070
    chain-level: 3       # 调用链长度等级，默认值为3（优化选项。系统中每个请求大致调用链平均长度，估算值。）
    
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
  instance:
    instance-id: springCloud-provider-order #eureka后面的名字
    prefer-ip-address: true #鼠标放到eureka后面的名字左下角显示ip
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间，默认是30秒
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔就表示注册中心挂了（默认是90秒）
    status-page-url: http://localhost:${server.port}/swagger-ui.html
    
info:
  app.name: springcloud-provider-order
  company.name: enjoy11
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
management:
    endpoints:
        web:
            exposure: 
                include: '*'