spring:
    profiles:
        active:
        - dev
---
server:
    port: 8095
  
spring:
  application:
    name: springCloud-redis #eureka前面的名字
  profiles: dev
  redis:
    database: 0
    host: 119.61.21.185
    port: 15019
    password: ph123456
    jedis:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 200
        min-idle: 0
    timeout: 5000
    
feign: 
  hystrix: 
    enabled: true
  compression: 
    request: 
      enabled: true 
      mime-types: #可以被压缩的类型 
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 #超过2048字节压缩
    
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
  instance:
    instance-id: springCloud-redis #eureka后面的名字
    prefer-ip-address: true #鼠标放到eureka后面的名字左下角显示ip
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间，默认是30秒
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔就表示注册中心挂了（默认是90秒）
    
info:
  app.name: springcloud-redis
  company.name: enjoy11
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
logging:
  level: 
    org.springframework.boot: ERROR  #关闭spring启动时无用日志

  
management:
    endpoints:
        web:
            exposure: 
                include: '*'
                
---

server:
    port: 8095
  
spring:
  application:
    name: springCloud-redis #eureka前面的名字
  profiles: beta
    
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7002/eureka
  instance:
    instance-id: springCloud-provider-product #eureka后面的名字
    prefer-ip-address: true #鼠标放到eureka后面的名字左下角显示ip
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间，默认是30秒
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔就表示注册中心挂了（默认是90秒）
    
info:
  app.name: springCloud-provider-product
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
management:
    endpoints:
        web:
            exposure: 
                include: '*'