spring:
    profiles:
        active:
        - dev
---
server:
    port: 8080
mybatis:
  mapper-locations:
  - classpath:mapping/*.xml
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.61.21.185:15018/springcloud?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ph123456
  application:
    name: springCloud-provider-product #eureka前面的名字
  profiles: dev
  
logging:
  level: 
    cn.enjoy.mapper: info
    org.springframework.boot.autoconfigure: ERROR
    
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
  instance:
    instance-id: springCloud-provider-product #eureka后面的名字
    prefer-ip-address: true #鼠标放到eureka后面的名字左下角显示ip
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间，默认是30秒
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔就表示注册中心挂了（默认是90秒）
    
info:
  app.name: springcloud-provider-product11
  company.name: enjoy11
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
management:
    endpoints:
        web:
            exposure: 
                include: '*'
                
---

server:
    port: 8081
mybatis:
  mapper-locations:
  - classpath:mapping/*.xml
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.61.21.185:15018/springcloud?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ph123456
  application:
    name: springCloud-provider-product #eureka前面的名字
  profiles: beta
  
logging:
  level:
    cn.enjoy.mapper: info
    org.springframework.boot.autoconfigure: ERROR 
    
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7002/eureka
  instance:
    instance-id: springCloud-provider-product #eureka后面的名字
    prefer-ip-address: true #鼠标放到eureka后面的名字左下角显示ip
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间，默认是30秒
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔就表示注册中心挂了（默认是90秒）
    
info:
  app.name: springCloud-provider-product
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  
management:
    endpoints:
        web:
            exposure: 
                include: '*'
